### ISSUE TITLE
Version 0.01 crash when openning the savefile

### ISSUE THREAD

**Issue by SuperN0va** [turtle-insect/OctopathTraveler2#1]
Bug Report
What's the issue you encountered?
version0.01 crash

How can the issue be reproduced?
After open the save file
Crash Report
N/A

System  Version
WIN 10 22H2

**Comment by turtle-insect** [comment]
Can you give me the save data from that time?

**Comment by SuperN0va** [comment]
[Jack - 2023.02.27 @ 08.44.08.zip](https://github.com/turtle-insect/OctopathTraveler2/files/10860887/Jack.-.2023.02.27.%40.08.44.08.zip)

**Comment by turtle-insect** [comment]
Successfully loaded here.

**Comment by SuperN0va** [comment]
I tried on Win11 and on admin mode，still crash，is that the zip file problem？I‘m not sure since currently i dont have any software like VSCode for me to build the code

**Comment by SuperN0va** [comment]
oh, i rebuild the source code and it works fine now. not sure why it behave bad on release version. still thanks for your work, really appreciate
